// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module forward_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv_layer_5_120_1_0_5_5_16_input_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_input_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_input_data_V_q0,
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0,
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0,
        conv_layer_5_120_1_0_5_5_16_output_data_V_q0,
        conv_layer_5_120_1_0_5_5_16_W_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_W_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_W_data_V_q0,
        conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0,
        conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0,
        conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0,
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0,
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0,
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0,
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0,
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0,
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0,
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0,
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] conv_layer_5_120_1_0_5_5_16_input_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_input_data_V_ce0;
input  [15:0] conv_layer_5_120_1_0_5_5_16_input_data_V_q0;
output  [6:0] conv_layer_5_120_1_0_5_5_16_output_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_output_data_V_ce0;
output   conv_layer_5_120_1_0_5_5_16_output_data_V_we0;
output  [15:0] conv_layer_5_120_1_0_5_5_16_output_data_V_d0;
input  [15:0] conv_layer_5_120_1_0_5_5_16_output_data_V_q0;
output  [15:0] conv_layer_5_120_1_0_5_5_16_W_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_W_data_V_ce0;
input  [15:0] conv_layer_5_120_1_0_5_5_16_W_data_V_q0;
output  [8:0] conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0;
output   conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0;
output  [15:0] conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0;
input  [15:0] conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0;
output  [6:0] conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0;
output   conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0;
output  [15:0] conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0;
input  [15:0] conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0;
output  [6:0] conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0;
output   conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0;
output   conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0;
output  [14:0] conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0;
input  [14:0] conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] conv_layer_5_120_1_0_5_5_16_output_data_V_address0;
reg conv_layer_5_120_1_0_5_5_16_output_data_V_ce0;
reg conv_layer_5_120_1_0_5_5_16_output_data_V_we0;
reg[15:0] conv_layer_5_120_1_0_5_5_16_output_data_V_d0;
reg[6:0] conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0;
reg conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0;
reg conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0;
reg[6:0] conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0;
reg conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0;
reg conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] p_i0_0_i_cast3_fu_141_p1;
reg   [63:0] p_i0_0_i_cast3_reg_218;
wire    ap_CS_fsm_state3;
wire   [6:0] p_i0_fu_152_p2;
reg   [6:0] p_i0_reg_226;
wire   [0:0] tmp_fu_146_p2;
wire   [6:0] iz_0_i_fu_164_p2;
reg   [6:0] iz_0_i_reg_239;
wire    ap_CS_fsm_state5;
wire   [63:0] tmp_10_0_i_fu_170_p1;
reg   [63:0] tmp_10_0_i_reg_244;
wire   [0:0] exitcond_0_i_fu_158_p2;
wire   [63:0] p_i0_0_i1_cast1_fu_196_p1;
reg   [63:0] p_i0_0_i1_cast1_reg_254;
wire    ap_CS_fsm_state7;
wire   [6:0] p_i0_5_fu_207_p2;
reg   [6:0] p_i0_5_reg_262;
wire   [0:0] tmp_s_fu_201_p2;
wire    grp_forward_conv_2_fu_129_ap_start;
wire    grp_forward_conv_2_fu_129_ap_done;
wire    grp_forward_conv_2_fu_129_ap_idle;
wire    grp_forward_conv_2_fu_129_ap_ready;
wire   [8:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0;
wire   [6:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0;
wire   [15:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0;
wire   [15:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0;
wire   [8:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0;
wire    grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0;
wire   [15:0] grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0;
reg   [6:0] p_i0_0_i_reg_96;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
reg   [6:0] p_z_assign_0_i_reg_107;
wire    ap_CS_fsm_state6;
reg   [6:0] p_i0_0_i1_reg_118;
wire    ap_CS_fsm_state8;
reg    grp_forward_conv_2_fu_129_ap_start_reg;
wire   [15:0] extLd_fu_213_p1;
wire   [0:0] tmp_72_fu_179_p3;
wire   [14:0] tmp_71_fu_175_p1;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_forward_conv_2_fu_129_ap_start_reg = 1'b0;
end

forward_conv_2 grp_forward_conv_2_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_conv_2_fu_129_ap_start),
    .ap_done(grp_forward_conv_2_fu_129_ap_done),
    .ap_idle(grp_forward_conv_2_fu_129_ap_idle),
    .ap_ready(grp_forward_conv_2_fu_129_ap_ready),
    .conv_layer_5_120_1_0_5_5_16_input_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0),
    .conv_layer_5_120_1_0_5_5_16_input_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0),
    .conv_layer_5_120_1_0_5_5_16_input_data_V_q0(conv_layer_5_120_1_0_5_5_16_input_data_V_q0),
    .conv_layer_5_120_1_0_5_5_16_output_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0),
    .conv_layer_5_120_1_0_5_5_16_output_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0),
    .conv_layer_5_120_1_0_5_5_16_output_data_V_we0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0),
    .conv_layer_5_120_1_0_5_5_16_output_data_V_d0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0),
    .conv_layer_5_120_1_0_5_5_16_W_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0),
    .conv_layer_5_120_1_0_5_5_16_W_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0),
    .conv_layer_5_120_1_0_5_5_16_W_data_V_q0(conv_layer_5_120_1_0_5_5_16_W_data_V_q0),
    .conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0),
    .conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0),
    .conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0),
    .conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0),
    .conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0(conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_conv_2_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_forward_conv_2_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_forward_conv_2_fu_129_ap_ready == 1'b1)) begin
            grp_forward_conv_2_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_0_i_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_i0_0_i1_reg_118 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_i0_0_i1_reg_118 <= p_i0_5_reg_262;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_i0_0_i_reg_96 <= p_i0_reg_226;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_forward_conv_2_fu_129_ap_done == 1'b1))) begin
        p_i0_0_i_reg_96 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_z_assign_0_i_reg_107 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_z_assign_0_i_reg_107 <= iz_0_i_reg_239;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        iz_0_i_reg_239 <= iz_0_i_fu_164_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_i0_0_i1_cast1_reg_254[6 : 0] <= p_i0_0_i1_cast1_fu_196_p1[6 : 0];
        p_i0_5_reg_262 <= p_i0_5_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_i0_0_i_cast3_reg_218[6 : 0] <= p_i0_0_i_cast3_fu_141_p1[6 : 0];
        p_i0_reg_226 <= p_i0_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_0_i_fu_158_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_10_0_i_reg_244[6 : 0] <= tmp_10_0_i_fu_170_p1[6 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state7) & (tmp_s_fu_201_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (tmp_s_fu_201_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = p_i0_0_i1_cast1_reg_254;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = p_i0_0_i_cast3_fu_141_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0;
    end else begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8))) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0;
    end else begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 = extLd_fu_213_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0;
    end else begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0;
    end else begin
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 = tmp_10_0_i_fu_170_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 = p_i0_0_i_cast3_reg_218;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0 = 1'b1;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0 = 1'b1;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 = p_i0_0_i1_cast1_fu_196_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 = tmp_10_0_i_reg_244;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0 = 1'b1;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0 = 1'b1;
    end else begin
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_forward_conv_2_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_0_i_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (tmp_s_fu_201_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign conv_layer_5_120_1_0_5_5_16_W_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0;

assign conv_layer_5_120_1_0_5_5_16_W_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0;

assign conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0;

assign conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0;

assign conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0;

assign conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0;

assign conv_layer_5_120_1_0_5_5_16_input_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0;

assign conv_layer_5_120_1_0_5_5_16_input_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0;

assign conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0 = conv_layer_5_120_1_0_5_5_16_output_data_V_q0;

assign conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0 = ((tmp_72_fu_179_p3[0:0] === 1'b1) ? 15'd0 : tmp_71_fu_175_p1);

assign exitcond_0_i_fu_158_p2 = ((p_z_assign_0_i_reg_107 == 7'd120) ? 1'b1 : 1'b0);

assign extLd_fu_213_p1 = conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0;

assign grp_forward_conv_2_fu_129_ap_start = grp_forward_conv_2_fu_129_ap_start_reg;

assign iz_0_i_fu_164_p2 = (p_z_assign_0_i_reg_107 + 7'd1);

assign p_i0_0_i1_cast1_fu_196_p1 = p_i0_0_i1_reg_118;

assign p_i0_0_i_cast3_fu_141_p1 = p_i0_0_i_reg_96;

assign p_i0_5_fu_207_p2 = (p_i0_0_i1_reg_118 + 7'd1);

assign p_i0_fu_152_p2 = (p_i0_0_i_reg_96 + 7'd1);

assign tmp_10_0_i_fu_170_p1 = p_z_assign_0_i_reg_107;

assign tmp_71_fu_175_p1 = conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0[14:0];

assign tmp_72_fu_179_p3 = conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0[32'd15];

assign tmp_fu_146_p2 = ((p_i0_0_i_reg_96 == 7'd120) ? 1'b1 : 1'b0);

assign tmp_s_fu_201_p2 = ((p_i0_0_i1_reg_118 == 7'd120) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    p_i0_0_i_cast3_reg_218[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_10_0_i_reg_244[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    p_i0_0_i1_cast1_reg_254[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //forward_4
