// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "forward_4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic forward_4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic forward_4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> forward_4::ap_ST_fsm_state1 = "1";
const sc_lv<8> forward_4::ap_ST_fsm_state2 = "10";
const sc_lv<8> forward_4::ap_ST_fsm_state3 = "100";
const sc_lv<8> forward_4::ap_ST_fsm_state4 = "1000";
const sc_lv<8> forward_4::ap_ST_fsm_state5 = "10000";
const sc_lv<8> forward_4::ap_ST_fsm_state6 = "100000";
const sc_lv<8> forward_4::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> forward_4::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> forward_4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> forward_4::ap_const_lv32_2 = "10";
const sc_lv<1> forward_4::ap_const_lv1_0 = "0";
const sc_lv<32> forward_4::ap_const_lv32_4 = "100";
const sc_lv<32> forward_4::ap_const_lv32_6 = "110";
const sc_lv<7> forward_4::ap_const_lv7_0 = "0000000";
const sc_lv<32> forward_4::ap_const_lv32_1 = "1";
const sc_lv<32> forward_4::ap_const_lv32_3 = "11";
const sc_lv<32> forward_4::ap_const_lv32_5 = "101";
const sc_lv<1> forward_4::ap_const_lv1_1 = "1";
const sc_lv<32> forward_4::ap_const_lv32_7 = "111";
const sc_lv<7> forward_4::ap_const_lv7_78 = "1111000";
const sc_lv<7> forward_4::ap_const_lv7_1 = "1";
const sc_lv<32> forward_4::ap_const_lv32_F = "1111";
const sc_lv<15> forward_4::ap_const_lv15_0 = "000000000000000";
const bool forward_4::ap_const_boolean_1 = true;

forward_4::forward_4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_forward_conv_2_fu_129 = new forward_conv_2("grp_forward_conv_2_fu_129");
    grp_forward_conv_2_fu_129->ap_clk(ap_clk);
    grp_forward_conv_2_fu_129->ap_rst(ap_rst);
    grp_forward_conv_2_fu_129->ap_start(grp_forward_conv_2_fu_129_ap_start);
    grp_forward_conv_2_fu_129->ap_done(grp_forward_conv_2_fu_129_ap_done);
    grp_forward_conv_2_fu_129->ap_idle(grp_forward_conv_2_fu_129_ap_idle);
    grp_forward_conv_2_fu_129->ap_ready(grp_forward_conv_2_fu_129_ap_ready);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_input_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_input_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_input_data_V_q0(conv_layer_5_120_1_0_5_5_16_input_data_V_q0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_output_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_output_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_output_data_V_we0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_output_data_V_d0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_W_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_W_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_W_data_V_q0(conv_layer_5_120_1_0_5_5_16_W_data_V_q0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0(grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0);
    grp_forward_conv_2_fu_129->conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0(conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_s_fu_201_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_s_fu_201_p2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_W_data_V_address0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_input_data_V_address0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_output_data_V_address0);
    sensitive << ( p_i0_0_i_cast3_fu_141_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_i0_0_i1_cast1_reg_254 );
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_output_data_V_d0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( extLd_fu_213_p1 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_output_data_V_we0);
    sensitive << ( grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0);
    sensitive << ( p_i0_0_i_cast3_reg_218 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_10_0_i_fu_170_p1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0);
    sensitive << ( conv_layer_5_120_1_0_5_5_16_output_data_V_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0);
    sensitive << ( tmp_10_0_i_reg_244 );
    sensitive << ( p_i0_0_i1_cast1_fu_196_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_72_fu_179_p3 );
    sensitive << ( tmp_71_fu_175_p1 );

    SC_METHOD(thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond_0_i_fu_158_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_z_assign_0_i_reg_107 );

    SC_METHOD(thread_extLd_fu_213_p1);
    sensitive << ( conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0 );

    SC_METHOD(thread_grp_forward_conv_2_fu_129_ap_start);
    sensitive << ( grp_forward_conv_2_fu_129_ap_start_reg );

    SC_METHOD(thread_iz_0_i_fu_164_p2);
    sensitive << ( p_z_assign_0_i_reg_107 );

    SC_METHOD(thread_p_i0_0_i1_cast1_fu_196_p1);
    sensitive << ( p_i0_0_i1_reg_118 );

    SC_METHOD(thread_p_i0_0_i_cast3_fu_141_p1);
    sensitive << ( p_i0_0_i_reg_96 );

    SC_METHOD(thread_p_i0_5_fu_207_p2);
    sensitive << ( p_i0_0_i1_reg_118 );

    SC_METHOD(thread_p_i0_fu_152_p2);
    sensitive << ( p_i0_0_i_reg_96 );

    SC_METHOD(thread_tmp_10_0_i_fu_170_p1);
    sensitive << ( p_z_assign_0_i_reg_107 );

    SC_METHOD(thread_tmp_71_fu_175_p1);
    sensitive << ( conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0 );

    SC_METHOD(thread_tmp_72_fu_179_p3);
    sensitive << ( conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0 );

    SC_METHOD(thread_tmp_fu_146_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_i0_0_i_reg_96 );

    SC_METHOD(thread_tmp_s_fu_201_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_i0_0_i1_reg_118 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_fu_146_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond_0_i_fu_158_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_s_fu_201_p2 );
    sensitive << ( grp_forward_conv_2_fu_129_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    ap_CS_fsm = "00000001";
    grp_forward_conv_2_fu_129_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "forward_4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_input_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_input_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_input_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_input_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_input_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_input_data_V_q0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_output_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_output_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_output_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_output_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_output_data_V_we0, "(port)conv_layer_5_120_1_0_5_5_16_output_data_V_we0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_output_data_V_d0, "(port)conv_layer_5_120_1_0_5_5_16_output_data_V_d0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_output_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_output_data_V_q0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_W_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_W_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_W_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_W_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_W_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_W_data_V_q0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0, "(port)conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0, "(port)conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_inpad_data_V_q0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0");
    sc_trace(mVcdFile, conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0, "(port)conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_i0_0_i_cast3_fu_141_p1, "p_i0_0_i_cast3_fu_141_p1");
    sc_trace(mVcdFile, p_i0_0_i_cast3_reg_218, "p_i0_0_i_cast3_reg_218");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, p_i0_fu_152_p2, "p_i0_fu_152_p2");
    sc_trace(mVcdFile, p_i0_reg_226, "p_i0_reg_226");
    sc_trace(mVcdFile, tmp_fu_146_p2, "tmp_fu_146_p2");
    sc_trace(mVcdFile, iz_0_i_fu_164_p2, "iz_0_i_fu_164_p2");
    sc_trace(mVcdFile, iz_0_i_reg_239, "iz_0_i_reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_10_0_i_fu_170_p1, "tmp_10_0_i_fu_170_p1");
    sc_trace(mVcdFile, tmp_10_0_i_reg_244, "tmp_10_0_i_reg_244");
    sc_trace(mVcdFile, exitcond_0_i_fu_158_p2, "exitcond_0_i_fu_158_p2");
    sc_trace(mVcdFile, p_i0_0_i1_cast1_fu_196_p1, "p_i0_0_i1_cast1_fu_196_p1");
    sc_trace(mVcdFile, p_i0_0_i1_cast1_reg_254, "p_i0_0_i1_cast1_reg_254");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, p_i0_5_fu_207_p2, "p_i0_5_fu_207_p2");
    sc_trace(mVcdFile, p_i0_5_reg_262, "p_i0_5_reg_262");
    sc_trace(mVcdFile, tmp_s_fu_201_p2, "tmp_s_fu_201_p2");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_ap_start, "grp_forward_conv_2_fu_129_ap_start");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_ap_done, "grp_forward_conv_2_fu_129_ap_done");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_ap_idle, "grp_forward_conv_2_fu_129_ap_idle");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_ap_ready, "grp_forward_conv_2_fu_129_ap_ready");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0, "grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0");
    sc_trace(mVcdFile, p_i0_0_i_reg_96, "p_i0_0_i_reg_96");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, p_z_assign_0_i_reg_107, "p_z_assign_0_i_reg_107");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, p_i0_0_i1_reg_118, "p_i0_0_i1_reg_118");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_forward_conv_2_fu_129_ap_start_reg, "grp_forward_conv_2_fu_129_ap_start_reg");
    sc_trace(mVcdFile, extLd_fu_213_p1, "extLd_fu_213_p1");
    sc_trace(mVcdFile, tmp_72_fu_179_p3, "tmp_72_fu_179_p3");
    sc_trace(mVcdFile, tmp_71_fu_175_p1, "tmp_71_fu_175_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

forward_4::~forward_4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_forward_conv_2_fu_129;
}

void forward_4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_forward_conv_2_fu_129_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_forward_conv_2_fu_129_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_forward_conv_2_fu_129_ap_ready.read())) {
            grp_forward_conv_2_fu_129_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond_0_i_fu_158_p2.read(), ap_const_lv1_1))) {
        p_i0_0_i1_reg_118 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_i0_0_i1_reg_118 = p_i0_5_reg_262.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_i0_0_i_reg_96 = p_i0_reg_226.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_forward_conv_2_fu_129_ap_done.read(), ap_const_logic_1))) {
        p_i0_0_i_reg_96 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_fu_146_p2.read(), ap_const_lv1_1))) {
        p_z_assign_0_i_reg_107 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_z_assign_0_i_reg_107 = iz_0_i_reg_239.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        iz_0_i_reg_239 = iz_0_i_fu_164_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_i0_0_i1_cast1_reg_254 = p_i0_0_i1_cast1_fu_196_p1.read();
        p_i0_5_reg_262 = p_i0_5_fu_207_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_i0_0_i_cast3_reg_218 = p_i0_0_i_cast3_fu_141_p1.read();
        p_i0_reg_226 = p_i0_fu_152_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_0_i_fu_158_p2.read()))) {
        tmp_10_0_i_reg_244 = tmp_10_0_i_fu_170_p1.read();
    }
}

void forward_4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void forward_4::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void forward_4::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void forward_4::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void forward_4::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void forward_4::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void forward_4::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void forward_4::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void forward_4::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(tmp_s_fu_201_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void forward_4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void forward_4::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(tmp_s_fu_201_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_W_data_V_address0() {
    conv_layer_5_120_1_0_5_5_16_W_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_address0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0() {
    conv_layer_5_120_1_0_5_5_16_W_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_W_data_V_ce0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0() {
    conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_address0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0() {
    conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_ce0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0() {
    conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_d0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0() {
    conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_inpad_data_V_we0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_input_data_V_address0() {
    conv_layer_5_120_1_0_5_5_16_input_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_address0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0() {
    conv_layer_5_120_1_0_5_5_16_input_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_input_data_V_ce0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_output_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 =  (sc_lv<7>) (p_i0_0_i1_cast1_reg_254.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 =  (sc_lv<7>) (p_i0_0_i_cast3_fu_141_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_address0.read();
    } else {
        conv_layer_5_120_1_0_5_5_16_output_data_V_address0 = "XXXXXXX";
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_ce0.read();
    } else {
        conv_layer_5_120_1_0_5_5_16_output_data_V_ce0 = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_output_data_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 = extLd_fu_213_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_d0.read();
    } else {
        conv_layer_5_120_1_0_5_5_16_output_data_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_output_data_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = grp_forward_conv_2_fu_129_conv_layer_5_120_1_0_5_5_16_output_data_V_we0.read();
    } else {
        conv_layer_5_120_1_0_5_5_16_output_data_V_we0 = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 =  (sc_lv<7>) (tmp_10_0_i_fu_170_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 =  (sc_lv<7>) (p_i0_0_i_cast3_reg_218.read());
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_address0 = "XXXXXXX";
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0 = ap_const_logic_1;
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_ce0 = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0() {
    conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_d0 = conv_layer_5_120_1_0_5_5_16_output_data_V_q0.read();
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0 = ap_const_logic_1;
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_we0 = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 =  (sc_lv<7>) (p_i0_0_i1_cast1_fu_196_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 =  (sc_lv<7>) (tmp_10_0_i_reg_244.read());
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_address0 = "XXXXXXX";
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0 = ap_const_logic_1;
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_ce0 = ap_const_logic_0;
    }
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0() {
    conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_d0 = (!tmp_72_fu_179_p3.read()[0].is_01())? sc_lv<15>(): ((tmp_72_fu_179_p3.read()[0].to_bool())? ap_const_lv15_0: tmp_71_fu_175_p1.read());
}

void forward_4::thread_conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0 = ap_const_logic_1;
    } else {
        conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_we0 = ap_const_logic_0;
    }
}

void forward_4::thread_exitcond_0_i_fu_158_p2() {
    exitcond_0_i_fu_158_p2 = (!p_z_assign_0_i_reg_107.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(p_z_assign_0_i_reg_107.read() == ap_const_lv7_78);
}

void forward_4::thread_extLd_fu_213_p1() {
    extLd_fu_213_p1 = esl_zext<16,15>(conv_layer_5_120_1_0_5_5_16_relu1_output_data_V_q0.read());
}

void forward_4::thread_grp_forward_conv_2_fu_129_ap_start() {
    grp_forward_conv_2_fu_129_ap_start = grp_forward_conv_2_fu_129_ap_start_reg.read();
}

void forward_4::thread_iz_0_i_fu_164_p2() {
    iz_0_i_fu_164_p2 = (!p_z_assign_0_i_reg_107.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_z_assign_0_i_reg_107.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void forward_4::thread_p_i0_0_i1_cast1_fu_196_p1() {
    p_i0_0_i1_cast1_fu_196_p1 = esl_zext<64,7>(p_i0_0_i1_reg_118.read());
}

void forward_4::thread_p_i0_0_i_cast3_fu_141_p1() {
    p_i0_0_i_cast3_fu_141_p1 = esl_zext<64,7>(p_i0_0_i_reg_96.read());
}

void forward_4::thread_p_i0_5_fu_207_p2() {
    p_i0_5_fu_207_p2 = (!p_i0_0_i1_reg_118.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_i0_0_i1_reg_118.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void forward_4::thread_p_i0_fu_152_p2() {
    p_i0_fu_152_p2 = (!p_i0_0_i_reg_96.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(p_i0_0_i_reg_96.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void forward_4::thread_tmp_10_0_i_fu_170_p1() {
    tmp_10_0_i_fu_170_p1 = esl_zext<64,7>(p_z_assign_0_i_reg_107.read());
}

void forward_4::thread_tmp_71_fu_175_p1() {
    tmp_71_fu_175_p1 = conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0.read().range(15-1, 0);
}

void forward_4::thread_tmp_72_fu_179_p3() {
    tmp_72_fu_179_p3 = conv_layer_5_120_1_0_5_5_16_relu1_input_data_V_q0.read().range(15, 15);
}

void forward_4::thread_tmp_fu_146_p2() {
    tmp_fu_146_p2 = (!p_i0_0_i_reg_96.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(p_i0_0_i_reg_96.read() == ap_const_lv7_78);
}

void forward_4::thread_tmp_s_fu_201_p2() {
    tmp_s_fu_201_p2 = (!p_i0_0_i1_reg_118.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(p_i0_0_i1_reg_118.read() == ap_const_lv7_78);
}

void forward_4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_forward_conv_2_fu_129_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_fu_146_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond_0_i_fu_158_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(tmp_s_fu_201_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

