// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "forward_pool_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic forward_pool_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic forward_pool_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> forward_pool_1::ap_ST_fsm_state1 = "1";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state2 = "10";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state3 = "100";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state4 = "1000";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state5 = "10000";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state6 = "100000";
const sc_lv<7> forward_pool_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> forward_pool_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> forward_pool_1::ap_const_lv32_1 = "1";
const sc_lv<1> forward_pool_1::ap_const_lv1_0 = "0";
const sc_lv<32> forward_pool_1::ap_const_lv32_2 = "10";
const sc_lv<32> forward_pool_1::ap_const_lv32_3 = "11";
const sc_lv<32> forward_pool_1::ap_const_lv32_4 = "100";
const sc_lv<1> forward_pool_1::ap_const_lv1_1 = "1";
const sc_lv<32> forward_pool_1::ap_const_lv32_5 = "101";
const sc_lv<32> forward_pool_1::ap_const_lv32_6 = "110";
const sc_lv<3> forward_pool_1::ap_const_lv3_0 = "000";
const sc_lv<5> forward_pool_1::ap_const_lv5_0 = "00000";
const sc_lv<9> forward_pool_1::ap_const_lv9_0 = "000000000";
const sc_lv<11> forward_pool_1::ap_const_lv11_0 = "00000000000";
const sc_lv<16> forward_pool_1::ap_const_lv16_0 = "0000000000000000";
const sc_lv<3> forward_pool_1::ap_const_lv3_5 = "101";
const sc_lv<3> forward_pool_1::ap_const_lv3_1 = "1";
const sc_lv<4> forward_pool_1::ap_const_lv4_2 = "10";
const sc_lv<2> forward_pool_1::ap_const_lv2_0 = "00";
const sc_lv<11> forward_pool_1::ap_const_lv11_64 = "1100100";
const sc_lv<9> forward_pool_1::ap_const_lv9_19 = "11001";
const sc_lv<5> forward_pool_1::ap_const_lv5_10 = "10000";
const sc_lv<5> forward_pool_1::ap_const_lv5_1 = "1";
const sc_lv<32> forward_pool_1::ap_const_lv32_F = "1111";
const sc_lv<17> forward_pool_1::ap_const_lv17_0 = "00000000000000000";
const sc_lv<32> forward_pool_1::ap_const_lv32_10 = "10000";
const bool forward_pool_1::ap_const_boolean_1 = true;

forward_pool_1::forward_pool_1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_191_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_191_p2 );

    SC_METHOD(thread_avg_V_fu_444_p2);
    sensitive << ( pool_layer_2_2_1_10_10_16_input_data_V_q0 );
    sensitive << ( p_Val2_s_reg_166 );

    SC_METHOD(thread_ch_fu_299_p2);
    sensitive << ( p_z_assign_reg_110 );

    SC_METHOD(thread_exitcond1_fu_229_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_y_assign_3_reg_99 );

    SC_METHOD(thread_exitcond2_fu_191_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_x_assign_reg_88 );

    SC_METHOD(thread_exitcond_fu_293_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_z_assign_reg_110 );

    SC_METHOD(thread_h_1_fu_241_p3);
    sensitive << ( p_y_assign_3_reg_99 );

    SC_METHOD(thread_h_3_cast_fu_249_p1);
    sensitive << ( h_1_fu_241_p3 );

    SC_METHOD(thread_h_fu_432_p2);
    sensitive << ( p_y_assign_4_reg_178 );

    SC_METHOD(thread_next_mul2_fu_281_p2);
    sensitive << ( phi_mul1_reg_133 );

    SC_METHOD(thread_next_mul_fu_287_p2);
    sensitive << ( phi_mul_reg_121 );

    SC_METHOD(thread_o_x_fu_235_p2);
    sensitive << ( p_y_assign_3_reg_99 );

    SC_METHOD(thread_o_y_fu_197_p2);
    sensitive << ( p_x_assign_reg_88 );

    SC_METHOD(thread_p_neg_fu_346_p2);
    sensitive << ( tmp_51_tr_fu_334_p1 );

    SC_METHOD(thread_p_shl5_fu_253_p3);
    sensitive << ( p_y_assign_3_reg_99 );

    SC_METHOD(thread_p_x_assign_5_cast_fu_211_p1);
    sensitive << ( v_fu_203_p3 );

    SC_METHOD(thread_p_x_assign_cast7_fu_187_p1);
    sensitive << ( p_x_assign_reg_88 );

    SC_METHOD(thread_p_y_assign_3_cast6_fu_225_p1);
    sensitive << ( p_y_assign_3_reg_99 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_input_data_V_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_38_fu_427_p1 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_input_data_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_output_data_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_31_fu_329_p1 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_output_data_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_output_data_V_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_56_fu_338_p3 );
    sensitive << ( tmp_33_fu_380_p2 );
    sensitive << ( tmp_34_fu_386_p1 );

    SC_METHOD(thread_pool_layer_2_2_1_10_10_16_output_data_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_23_fu_309_p2 );

    SC_METHOD(thread_tmp1_fu_314_p2);
    sensitive << ( tmp_cast8_reg_514 );
    sensitive << ( p_x_assign_3_reg_156 );

    SC_METHOD(thread_tmp2_cast_fu_277_p1);
    sensitive << ( tmp2_fu_271_p2 );

    SC_METHOD(thread_tmp2_fu_271_p2);
    sensitive << ( p_y_assign_3_cast6_fu_225_p1 );
    sensitive << ( p_shl5_fu_253_p3 );

    SC_METHOD(thread_tmp3_fu_319_p2);
    sensitive << ( p_x_assign_cast7_reg_450 );
    sensitive << ( phi_mul_reg_121 );

    SC_METHOD(thread_tmp_21_fu_215_p2);
    sensitive << ( v_fu_203_p3 );

    SC_METHOD(thread_tmp_22_fu_261_p2);
    sensitive << ( h_1_fu_241_p3 );

    SC_METHOD(thread_tmp_23_cast_fu_221_p1);
    sensitive << ( tmp_21_fu_215_p2 );

    SC_METHOD(thread_tmp_23_fu_309_p2);
    sensitive << ( tmp_23_cast_reg_468 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_x_assign_3_reg_156 );

    SC_METHOD(thread_tmp_24_cast_fu_267_p1);
    sensitive << ( tmp_22_fu_261_p2 );

    SC_METHOD(thread_tmp_27_fu_362_p1);
    sensitive << ( tmp_s_fu_352_p4 );

    SC_METHOD(thread_tmp_29_fu_324_p2);
    sensitive << ( tmp2_cast_reg_491 );
    sensitive << ( tmp3_fu_319_p2 );

    SC_METHOD(thread_tmp_30_fu_366_p4);
    sensitive << ( t_V_reg_144 );

    SC_METHOD(thread_tmp_31_fu_329_p1);
    sensitive << ( tmp_29_fu_324_p2 );

    SC_METHOD(thread_tmp_32_fu_376_p1);
    sensitive << ( tmp_30_fu_366_p4 );

    SC_METHOD(thread_tmp_33_fu_380_p2);
    sensitive << ( tmp_27_fu_362_p1 );

    SC_METHOD(thread_tmp_34_fu_386_p1);
    sensitive << ( tmp_32_fu_376_p1 );

    SC_METHOD(thread_tmp_36_fu_399_p2);
    sensitive << ( tmp_24_cast_reg_486 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_y_assign_4_reg_178 );

    SC_METHOD(thread_tmp_37_fu_422_p2);
    sensitive << ( tmp1_reg_522 );
    sensitive << ( tmp_fu_416_p2 );

    SC_METHOD(thread_tmp_38_fu_427_p1);
    sensitive << ( tmp_37_fu_422_p2 );

    SC_METHOD(thread_tmp_51_tr_fu_334_p1);
    sensitive << ( t_V_reg_144 );

    SC_METHOD(thread_tmp_56_fu_338_p3);
    sensitive << ( t_V_reg_144 );

    SC_METHOD(thread_tmp_57_fu_404_p2);
    sensitive << ( p_y_assign_4_reg_178 );

    SC_METHOD(thread_tmp_58_fu_410_p2);
    sensitive << ( p_y_assign_4_reg_178 );

    SC_METHOD(thread_tmp_cast8_fu_305_p1);
    sensitive << ( phi_mul1_reg_133 );

    SC_METHOD(thread_tmp_fu_416_p2);
    sensitive << ( tmp_57_fu_404_p2 );
    sensitive << ( tmp_58_fu_410_p2 );

    SC_METHOD(thread_tmp_s_fu_352_p4);
    sensitive << ( p_neg_fu_346_p2 );

    SC_METHOD(thread_v_1_fu_438_p2);
    sensitive << ( p_x_assign_3_reg_156 );

    SC_METHOD(thread_v_fu_203_p3);
    sensitive << ( p_x_assign_reg_88 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_191_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond1_fu_229_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_293_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_23_fu_309_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_36_fu_399_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "forward_pool_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_input_data_V_address0, "(port)pool_layer_2_2_1_10_10_16_input_data_V_address0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_input_data_V_ce0, "(port)pool_layer_2_2_1_10_10_16_input_data_V_ce0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_input_data_V_q0, "(port)pool_layer_2_2_1_10_10_16_input_data_V_q0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_output_data_V_address0, "(port)pool_layer_2_2_1_10_10_16_output_data_V_address0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_output_data_V_ce0, "(port)pool_layer_2_2_1_10_10_16_output_data_V_ce0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_output_data_V_we0, "(port)pool_layer_2_2_1_10_10_16_output_data_V_we0");
    sc_trace(mVcdFile, pool_layer_2_2_1_10_10_16_output_data_V_d0, "(port)pool_layer_2_2_1_10_10_16_output_data_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_x_assign_cast7_fu_187_p1, "p_x_assign_cast7_fu_187_p1");
    sc_trace(mVcdFile, p_x_assign_cast7_reg_450, "p_x_assign_cast7_reg_450");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, o_y_fu_197_p2, "o_y_fu_197_p2");
    sc_trace(mVcdFile, o_y_reg_458, "o_y_reg_458");
    sc_trace(mVcdFile, p_x_assign_5_cast_fu_211_p1, "p_x_assign_5_cast_fu_211_p1");
    sc_trace(mVcdFile, p_x_assign_5_cast_reg_463, "p_x_assign_5_cast_reg_463");
    sc_trace(mVcdFile, exitcond2_fu_191_p2, "exitcond2_fu_191_p2");
    sc_trace(mVcdFile, tmp_23_cast_fu_221_p1, "tmp_23_cast_fu_221_p1");
    sc_trace(mVcdFile, tmp_23_cast_reg_468, "tmp_23_cast_reg_468");
    sc_trace(mVcdFile, o_x_fu_235_p2, "o_x_fu_235_p2");
    sc_trace(mVcdFile, o_x_reg_476, "o_x_reg_476");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, h_3_cast_fu_249_p1, "h_3_cast_fu_249_p1");
    sc_trace(mVcdFile, h_3_cast_reg_481, "h_3_cast_reg_481");
    sc_trace(mVcdFile, exitcond1_fu_229_p2, "exitcond1_fu_229_p2");
    sc_trace(mVcdFile, tmp_24_cast_fu_267_p1, "tmp_24_cast_fu_267_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_486, "tmp_24_cast_reg_486");
    sc_trace(mVcdFile, tmp2_cast_fu_277_p1, "tmp2_cast_fu_277_p1");
    sc_trace(mVcdFile, tmp2_cast_reg_491, "tmp2_cast_reg_491");
    sc_trace(mVcdFile, next_mul2_fu_281_p2, "next_mul2_fu_281_p2");
    sc_trace(mVcdFile, next_mul2_reg_496, "next_mul2_reg_496");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, next_mul_fu_287_p2, "next_mul_fu_287_p2");
    sc_trace(mVcdFile, next_mul_reg_501, "next_mul_reg_501");
    sc_trace(mVcdFile, ch_fu_299_p2, "ch_fu_299_p2");
    sc_trace(mVcdFile, ch_reg_509, "ch_reg_509");
    sc_trace(mVcdFile, tmp_cast8_fu_305_p1, "tmp_cast8_fu_305_p1");
    sc_trace(mVcdFile, tmp_cast8_reg_514, "tmp_cast8_reg_514");
    sc_trace(mVcdFile, exitcond_fu_293_p2, "exitcond_fu_293_p2");
    sc_trace(mVcdFile, tmp1_fu_314_p2, "tmp1_fu_314_p2");
    sc_trace(mVcdFile, tmp1_reg_522, "tmp1_reg_522");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_23_fu_309_p2, "tmp_23_fu_309_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_36_fu_399_p2, "tmp_36_fu_399_p2");
    sc_trace(mVcdFile, h_fu_432_p2, "h_fu_432_p2");
    sc_trace(mVcdFile, h_reg_535, "h_reg_535");
    sc_trace(mVcdFile, v_1_fu_438_p2, "v_1_fu_438_p2");
    sc_trace(mVcdFile, avg_V_fu_444_p2, "avg_V_fu_444_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, p_x_assign_reg_88, "p_x_assign_reg_88");
    sc_trace(mVcdFile, p_y_assign_3_reg_99, "p_y_assign_3_reg_99");
    sc_trace(mVcdFile, p_z_assign_reg_110, "p_z_assign_reg_110");
    sc_trace(mVcdFile, phi_mul_reg_121, "phi_mul_reg_121");
    sc_trace(mVcdFile, phi_mul1_reg_133, "phi_mul1_reg_133");
    sc_trace(mVcdFile, t_V_reg_144, "t_V_reg_144");
    sc_trace(mVcdFile, p_x_assign_3_reg_156, "p_x_assign_3_reg_156");
    sc_trace(mVcdFile, p_Val2_s_reg_166, "p_Val2_s_reg_166");
    sc_trace(mVcdFile, p_y_assign_4_reg_178, "p_y_assign_4_reg_178");
    sc_trace(mVcdFile, tmp_31_fu_329_p1, "tmp_31_fu_329_p1");
    sc_trace(mVcdFile, tmp_38_fu_427_p1, "tmp_38_fu_427_p1");
    sc_trace(mVcdFile, v_fu_203_p3, "v_fu_203_p3");
    sc_trace(mVcdFile, tmp_21_fu_215_p2, "tmp_21_fu_215_p2");
    sc_trace(mVcdFile, h_1_fu_241_p3, "h_1_fu_241_p3");
    sc_trace(mVcdFile, tmp_22_fu_261_p2, "tmp_22_fu_261_p2");
    sc_trace(mVcdFile, p_y_assign_3_cast6_fu_225_p1, "p_y_assign_3_cast6_fu_225_p1");
    sc_trace(mVcdFile, p_shl5_fu_253_p3, "p_shl5_fu_253_p3");
    sc_trace(mVcdFile, tmp2_fu_271_p2, "tmp2_fu_271_p2");
    sc_trace(mVcdFile, tmp3_fu_319_p2, "tmp3_fu_319_p2");
    sc_trace(mVcdFile, tmp_29_fu_324_p2, "tmp_29_fu_324_p2");
    sc_trace(mVcdFile, tmp_51_tr_fu_334_p1, "tmp_51_tr_fu_334_p1");
    sc_trace(mVcdFile, p_neg_fu_346_p2, "p_neg_fu_346_p2");
    sc_trace(mVcdFile, tmp_s_fu_352_p4, "tmp_s_fu_352_p4");
    sc_trace(mVcdFile, tmp_30_fu_366_p4, "tmp_30_fu_366_p4");
    sc_trace(mVcdFile, tmp_27_fu_362_p1, "tmp_27_fu_362_p1");
    sc_trace(mVcdFile, tmp_32_fu_376_p1, "tmp_32_fu_376_p1");
    sc_trace(mVcdFile, tmp_56_fu_338_p3, "tmp_56_fu_338_p3");
    sc_trace(mVcdFile, tmp_33_fu_380_p2, "tmp_33_fu_380_p2");
    sc_trace(mVcdFile, tmp_34_fu_386_p1, "tmp_34_fu_386_p1");
    sc_trace(mVcdFile, tmp_57_fu_404_p2, "tmp_57_fu_404_p2");
    sc_trace(mVcdFile, tmp_58_fu_410_p2, "tmp_58_fu_410_p2");
    sc_trace(mVcdFile, tmp_fu_416_p2, "tmp_fu_416_p2");
    sc_trace(mVcdFile, tmp_37_fu_422_p2, "tmp_37_fu_422_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

forward_pool_1::~forward_pool_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void forward_pool_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_23_fu_309_p2.read(), ap_const_lv1_1))) {
        p_Val2_s_reg_166 = t_V_reg_144.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Val2_s_reg_166 = avg_V_fu_444_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_36_fu_399_p2.read()))) {
        p_x_assign_3_reg_156 = v_1_fu_438_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_293_p2.read()))) {
        p_x_assign_3_reg_156 = p_x_assign_5_cast_reg_463.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_229_p2.read(), ap_const_lv1_1))) {
        p_x_assign_reg_88 = o_y_reg_458.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_x_assign_reg_88 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_293_p2.read(), ap_const_lv1_1))) {
        p_y_assign_3_reg_99 = o_x_reg_476.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_191_p2.read(), ap_const_lv1_0))) {
        p_y_assign_3_reg_99 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_23_fu_309_p2.read(), ap_const_lv1_1))) {
        p_y_assign_4_reg_178 = h_3_cast_reg_481.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_y_assign_4_reg_178 = h_reg_535.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_309_p2.read()))) {
        p_z_assign_reg_110 = ch_reg_509.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_229_p2.read()))) {
        p_z_assign_reg_110 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_309_p2.read()))) {
        phi_mul1_reg_133 = next_mul2_reg_496.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_229_p2.read()))) {
        phi_mul1_reg_133 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_309_p2.read()))) {
        phi_mul_reg_121 = next_mul_reg_501.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_229_p2.read()))) {
        phi_mul_reg_121 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_36_fu_399_p2.read()))) {
        t_V_reg_144 = p_Val2_s_reg_166.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_293_p2.read()))) {
        t_V_reg_144 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ch_reg_509 = ch_fu_299_p2.read();
        next_mul2_reg_496 = next_mul2_fu_281_p2.read();
        next_mul_reg_501 = next_mul_fu_287_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_229_p2.read()))) {
        h_3_cast_reg_481 = h_3_cast_fu_249_p1.read();
        tmp2_cast_reg_491 = tmp2_cast_fu_277_p1.read();
        tmp_24_cast_reg_486 = tmp_24_cast_fu_267_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_36_fu_399_p2.read()))) {
        h_reg_535 = h_fu_432_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        o_x_reg_476 = o_x_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        o_y_reg_458 = o_y_fu_197_p2.read();
        p_x_assign_cast7_reg_450 = p_x_assign_cast7_fu_187_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond2_fu_191_p2.read(), ap_const_lv1_0))) {
        p_x_assign_5_cast_reg_463 = p_x_assign_5_cast_fu_211_p1.read();
        tmp_23_cast_reg_468 = tmp_23_cast_fu_221_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_23_fu_309_p2.read(), ap_const_lv1_1))) {
        tmp1_reg_522 = tmp1_fu_314_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_293_p2.read()))) {
        tmp_cast8_reg_514 = tmp_cast8_fu_305_p1.read();
    }
}

void forward_pool_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void forward_pool_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void forward_pool_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void forward_pool_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void forward_pool_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void forward_pool_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void forward_pool_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void forward_pool_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_191_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void forward_pool_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void forward_pool_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_191_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void forward_pool_1::thread_avg_V_fu_444_p2() {
    avg_V_fu_444_p2 = (!pool_layer_2_2_1_10_10_16_input_data_V_q0.read().is_01() || !p_Val2_s_reg_166.read().is_01())? sc_lv<16>(): (sc_biguint<16>(pool_layer_2_2_1_10_10_16_input_data_V_q0.read()) + sc_biguint<16>(p_Val2_s_reg_166.read()));
}

void forward_pool_1::thread_ch_fu_299_p2() {
    ch_fu_299_p2 = (!p_z_assign_reg_110.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(p_z_assign_reg_110.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void forward_pool_1::thread_exitcond1_fu_229_p2() {
    exitcond1_fu_229_p2 = (!p_y_assign_3_reg_99.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(p_y_assign_3_reg_99.read() == ap_const_lv3_5);
}

void forward_pool_1::thread_exitcond2_fu_191_p2() {
    exitcond2_fu_191_p2 = (!p_x_assign_reg_88.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(p_x_assign_reg_88.read() == ap_const_lv3_5);
}

void forward_pool_1::thread_exitcond_fu_293_p2() {
    exitcond_fu_293_p2 = (!p_z_assign_reg_110.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(p_z_assign_reg_110.read() == ap_const_lv5_10);
}

void forward_pool_1::thread_h_1_fu_241_p3() {
    h_1_fu_241_p3 = esl_concat<3,1>(p_y_assign_3_reg_99.read(), ap_const_lv1_0);
}

void forward_pool_1::thread_h_3_cast_fu_249_p1() {
    h_3_cast_fu_249_p1 = esl_zext<32,4>(h_1_fu_241_p3.read());
}

void forward_pool_1::thread_h_fu_432_p2() {
    h_fu_432_p2 = (!ap_const_lv32_1.is_01() || !p_y_assign_4_reg_178.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(p_y_assign_4_reg_178.read()));
}

void forward_pool_1::thread_next_mul2_fu_281_p2() {
    next_mul2_fu_281_p2 = (!phi_mul1_reg_133.read().is_01() || !ap_const_lv11_64.is_01())? sc_lv<11>(): (sc_biguint<11>(phi_mul1_reg_133.read()) + sc_biguint<11>(ap_const_lv11_64));
}

void forward_pool_1::thread_next_mul_fu_287_p2() {
    next_mul_fu_287_p2 = (!phi_mul_reg_121.read().is_01() || !ap_const_lv9_19.is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_121.read()) + sc_biguint<9>(ap_const_lv9_19));
}

void forward_pool_1::thread_o_x_fu_235_p2() {
    o_x_fu_235_p2 = (!p_y_assign_3_reg_99.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_y_assign_3_reg_99.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void forward_pool_1::thread_o_y_fu_197_p2() {
    o_y_fu_197_p2 = (!p_x_assign_reg_88.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_x_assign_reg_88.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void forward_pool_1::thread_p_neg_fu_346_p2() {
    p_neg_fu_346_p2 = (!ap_const_lv17_0.is_01() || !tmp_51_tr_fu_334_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_bigint<17>(tmp_51_tr_fu_334_p1.read()));
}

void forward_pool_1::thread_p_shl5_fu_253_p3() {
    p_shl5_fu_253_p3 = esl_concat<3,2>(p_y_assign_3_reg_99.read(), ap_const_lv2_0);
}

void forward_pool_1::thread_p_x_assign_5_cast_fu_211_p1() {
    p_x_assign_5_cast_fu_211_p1 = esl_zext<32,4>(v_fu_203_p3.read());
}

void forward_pool_1::thread_p_x_assign_cast7_fu_187_p1() {
    p_x_assign_cast7_fu_187_p1 = esl_zext<9,3>(p_x_assign_reg_88.read());
}

void forward_pool_1::thread_p_y_assign_3_cast6_fu_225_p1() {
    p_y_assign_3_cast6_fu_225_p1 = esl_zext<5,3>(p_y_assign_3_reg_99.read());
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_input_data_V_address0() {
    pool_layer_2_2_1_10_10_16_input_data_V_address0 =  (sc_lv<11>) (tmp_38_fu_427_p1.read());
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_input_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_layer_2_2_1_10_10_16_input_data_V_ce0 = ap_const_logic_1;
    } else {
        pool_layer_2_2_1_10_10_16_input_data_V_ce0 = ap_const_logic_0;
    }
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_output_data_V_address0() {
    pool_layer_2_2_1_10_10_16_output_data_V_address0 =  (sc_lv<9>) (tmp_31_fu_329_p1.read());
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_output_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        pool_layer_2_2_1_10_10_16_output_data_V_ce0 = ap_const_logic_1;
    } else {
        pool_layer_2_2_1_10_10_16_output_data_V_ce0 = ap_const_logic_0;
    }
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_output_data_V_d0() {
    pool_layer_2_2_1_10_10_16_output_data_V_d0 = (!tmp_56_fu_338_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_56_fu_338_p3.read()[0].to_bool())? tmp_33_fu_380_p2.read(): tmp_34_fu_386_p1.read());
}

void forward_pool_1::thread_pool_layer_2_2_1_10_10_16_output_data_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_309_p2.read()))) {
        pool_layer_2_2_1_10_10_16_output_data_V_we0 = ap_const_logic_1;
    } else {
        pool_layer_2_2_1_10_10_16_output_data_V_we0 = ap_const_logic_0;
    }
}

void forward_pool_1::thread_tmp1_fu_314_p2() {
    tmp1_fu_314_p2 = (!p_x_assign_3_reg_156.read().is_01() || !tmp_cast8_reg_514.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_x_assign_3_reg_156.read()) + sc_biguint<32>(tmp_cast8_reg_514.read()));
}

void forward_pool_1::thread_tmp2_cast_fu_277_p1() {
    tmp2_cast_fu_277_p1 = esl_zext<9,5>(tmp2_fu_271_p2.read());
}

void forward_pool_1::thread_tmp2_fu_271_p2() {
    tmp2_fu_271_p2 = (!p_y_assign_3_cast6_fu_225_p1.read().is_01() || !p_shl5_fu_253_p3.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_y_assign_3_cast6_fu_225_p1.read()) + sc_biguint<5>(p_shl5_fu_253_p3.read()));
}

void forward_pool_1::thread_tmp3_fu_319_p2() {
    tmp3_fu_319_p2 = (!p_x_assign_cast7_reg_450.read().is_01() || !phi_mul_reg_121.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_x_assign_cast7_reg_450.read()) + sc_biguint<9>(phi_mul_reg_121.read()));
}

void forward_pool_1::thread_tmp_21_fu_215_p2() {
    tmp_21_fu_215_p2 = (!v_fu_203_p3.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(v_fu_203_p3.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void forward_pool_1::thread_tmp_22_fu_261_p2() {
    tmp_22_fu_261_p2 = (!h_1_fu_241_p3.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(h_1_fu_241_p3.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void forward_pool_1::thread_tmp_23_cast_fu_221_p1() {
    tmp_23_cast_fu_221_p1 = esl_zext<32,4>(tmp_21_fu_215_p2.read());
}

void forward_pool_1::thread_tmp_23_fu_309_p2() {
    tmp_23_fu_309_p2 = (!p_x_assign_3_reg_156.read().is_01() || !tmp_23_cast_reg_468.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_x_assign_3_reg_156.read()) < sc_bigint<32>(tmp_23_cast_reg_468.read()));
}

void forward_pool_1::thread_tmp_24_cast_fu_267_p1() {
    tmp_24_cast_fu_267_p1 = esl_zext<32,4>(tmp_22_fu_261_p2.read());
}

void forward_pool_1::thread_tmp_27_fu_362_p1() {
    tmp_27_fu_362_p1 = esl_zext<16,15>(tmp_s_fu_352_p4.read());
}

void forward_pool_1::thread_tmp_29_fu_324_p2() {
    tmp_29_fu_324_p2 = (!tmp3_fu_319_p2.read().is_01() || !tmp2_cast_reg_491.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp3_fu_319_p2.read()) + sc_biguint<9>(tmp2_cast_reg_491.read()));
}

void forward_pool_1::thread_tmp_30_fu_366_p4() {
    tmp_30_fu_366_p4 = t_V_reg_144.read().range(15, 2);
}

void forward_pool_1::thread_tmp_31_fu_329_p1() {
    tmp_31_fu_329_p1 = esl_zext<64,9>(tmp_29_fu_324_p2.read());
}

void forward_pool_1::thread_tmp_32_fu_376_p1() {
    tmp_32_fu_376_p1 = esl_sext<15,14>(tmp_30_fu_366_p4.read());
}

void forward_pool_1::thread_tmp_33_fu_380_p2() {
    tmp_33_fu_380_p2 = (!ap_const_lv16_0.is_01() || !tmp_27_fu_362_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(tmp_27_fu_362_p1.read()));
}

void forward_pool_1::thread_tmp_34_fu_386_p1() {
    tmp_34_fu_386_p1 = esl_zext<16,15>(tmp_32_fu_376_p1.read());
}

void forward_pool_1::thread_tmp_36_fu_399_p2() {
    tmp_36_fu_399_p2 = (!p_y_assign_4_reg_178.read().is_01() || !tmp_24_cast_reg_486.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_y_assign_4_reg_178.read()) < sc_bigint<32>(tmp_24_cast_reg_486.read()));
}

void forward_pool_1::thread_tmp_37_fu_422_p2() {
    tmp_37_fu_422_p2 = (!tmp1_reg_522.read().is_01() || !tmp_fu_416_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp1_reg_522.read()) + sc_biguint<32>(tmp_fu_416_p2.read()));
}

void forward_pool_1::thread_tmp_38_fu_427_p1() {
    tmp_38_fu_427_p1 = esl_sext<64,32>(tmp_37_fu_422_p2.read());
}

void forward_pool_1::thread_tmp_51_tr_fu_334_p1() {
    tmp_51_tr_fu_334_p1 = esl_sext<17,16>(t_V_reg_144.read());
}

void forward_pool_1::thread_tmp_56_fu_338_p3() {
    tmp_56_fu_338_p3 = t_V_reg_144.read().range(15, 15);
}

void forward_pool_1::thread_tmp_57_fu_404_p2() {
    tmp_57_fu_404_p2 = (!ap_const_lv32_3.is_01())? sc_lv<32>(): p_y_assign_4_reg_178.read() << (unsigned short)ap_const_lv32_3.to_uint();
}

void forward_pool_1::thread_tmp_58_fu_410_p2() {
    tmp_58_fu_410_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): p_y_assign_4_reg_178.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void forward_pool_1::thread_tmp_cast8_fu_305_p1() {
    tmp_cast8_fu_305_p1 = esl_zext<32,11>(phi_mul1_reg_133.read());
}

void forward_pool_1::thread_tmp_fu_416_p2() {
    tmp_fu_416_p2 = (!tmp_57_fu_404_p2.read().is_01() || !tmp_58_fu_410_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_57_fu_404_p2.read()) + sc_biguint<32>(tmp_58_fu_410_p2.read()));
}

void forward_pool_1::thread_tmp_s_fu_352_p4() {
    tmp_s_fu_352_p4 = p_neg_fu_346_p2.read().range(16, 2);
}

void forward_pool_1::thread_v_1_fu_438_p2() {
    v_1_fu_438_p2 = (!p_x_assign_3_reg_156.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(p_x_assign_3_reg_156.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void forward_pool_1::thread_v_fu_203_p3() {
    v_fu_203_p3 = esl_concat<3,1>(p_x_assign_reg_88.read(), ap_const_lv1_0);
}

void forward_pool_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond2_fu_191_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond1_fu_229_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond_fu_293_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_fu_309_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_36_fu_399_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

