// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _forward_1_HH_
#define _forward_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "forward_pool_1.h"

namespace ap_rtl {

struct forward_1 : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<11> > pool_layer_2_2_1_10_10_16_input_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_input_data_V_ce0;
    sc_in< sc_lv<16> > pool_layer_2_2_1_10_10_16_input_data_V_q0;
    sc_out< sc_lv<9> > pool_layer_2_2_1_10_10_16_output_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_output_data_V_ce0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_output_data_V_we0;
    sc_out< sc_lv<16> > pool_layer_2_2_1_10_10_16_output_data_V_d0;
    sc_in< sc_lv<16> > pool_layer_2_2_1_10_10_16_output_data_V_q0;
    sc_out< sc_lv<9> > pool_layer_2_2_1_10_10_16_relu1_input_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_relu1_input_data_V_ce0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_relu1_input_data_V_we0;
    sc_out< sc_lv<16> > pool_layer_2_2_1_10_10_16_relu1_input_data_V_d0;
    sc_in< sc_lv<16> > pool_layer_2_2_1_10_10_16_relu1_input_data_V_q0;
    sc_out< sc_lv<9> > pool_layer_2_2_1_10_10_16_relu1_output_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_relu1_output_data_V_ce0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_relu1_output_data_V_we0;
    sc_out< sc_lv<15> > pool_layer_2_2_1_10_10_16_relu1_output_data_V_d0;
    sc_in< sc_lv<15> > pool_layer_2_2_1_10_10_16_relu1_output_data_V_q0;


    // Module declarations
    forward_1(sc_module_name name);
    SC_HAS_PROCESS(forward_1);

    ~forward_1();

    sc_trace_file* mVcdFile;

    forward_pool_1* grp_forward_pool_1_fu_180;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > p_i0_0_i_cast7_fu_188_p1;
    sc_signal< sc_lv<64> > p_i0_0_i_cast7_reg_331;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<9> > p_i0_fu_199_p2;
    sc_signal< sc_lv<9> > p_i0_reg_339;
    sc_signal< sc_lv<1> > tmp_fu_193_p2;
    sc_signal< sc_lv<9> > p_x_assign_cast6_fu_205_p1;
    sc_signal< sc_lv<9> > p_x_assign_cast6_reg_349;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > ix_fu_215_p2;
    sc_signal< sc_lv<3> > ix_reg_357;
    sc_signal< sc_lv<3> > iy_fu_231_p2;
    sc_signal< sc_lv<3> > iy_reg_365;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<9> > tmp1_cast_fu_251_p1;
    sc_signal< sc_lv<9> > tmp1_cast_reg_370;
    sc_signal< sc_lv<1> > exitcond2_i_fu_225_p2;
    sc_signal< sc_lv<5> > iz_fu_261_p2;
    sc_signal< sc_lv<5> > iz_reg_378;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<9> > next_mul_fu_267_p2;
    sc_signal< sc_lv<9> > next_mul_reg_383;
    sc_signal< sc_lv<1> > exitcond_i_fu_255_p2;
    sc_signal< sc_lv<64> > tmp_4_i_fu_283_p1;
    sc_signal< sc_lv<64> > tmp_4_i_reg_388;
    sc_signal< sc_lv<64> > p_i0_0_i1_cast3_fu_309_p1;
    sc_signal< sc_lv<64> > p_i0_0_i1_cast3_reg_398;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<9> > p_i0_2_fu_320_p2;
    sc_signal< sc_lv<9> > p_i0_2_reg_406;
    sc_signal< sc_lv<1> > tmp_s_fu_314_p2;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_ap_start;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_ap_done;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_ap_idle;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_ap_ready;
    sc_signal< sc_lv<11> > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_input_data_V_address0;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_input_data_V_ce0;
    sc_signal< sc_lv<9> > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_output_data_V_address0;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_output_data_V_ce0;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_output_data_V_we0;
    sc_signal< sc_lv<16> > grp_forward_pool_1_fu_180_pool_layer_2_2_1_10_10_16_output_data_V_d0;
    sc_signal< sc_lv<9> > p_i0_0_i_reg_114;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > p_x_assign_reg_125;
    sc_signal< sc_lv<3> > p_y_assign_reg_136;
    sc_signal< sc_lv<1> > exitcond1_i_fu_209_p2;
    sc_signal< sc_lv<5> > p_z_assign_reg_147;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<9> > phi_mul_reg_158;
    sc_signal< sc_lv<9> > p_i0_0_i1_reg_169;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > grp_forward_pool_1_fu_180_ap_start_reg;
    sc_signal< sc_lv<16> > extLd_fu_326_p1;
    sc_signal< sc_lv<5> > p_y_assign_cast5_fu_221_p1;
    sc_signal< sc_lv<5> > p_shl_i_fu_237_p3;
    sc_signal< sc_lv<5> > tmp1_fu_245_p2;
    sc_signal< sc_lv<9> > tmp2_fu_273_p2;
    sc_signal< sc_lv<9> > tmp_3_i_fu_278_p2;
    sc_signal< sc_lv<1> > tmp_78_fu_292_p3;
    sc_signal< sc_lv<15> > tmp_77_fu_288_p1;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<9> ap_const_lv9_190;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<9> ap_const_lv9_19;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<15> ap_const_lv15_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_i_fu_209_p2();
    void thread_exitcond2_i_fu_225_p2();
    void thread_exitcond_i_fu_255_p2();
    void thread_extLd_fu_326_p1();
    void thread_grp_forward_pool_1_fu_180_ap_start();
    void thread_ix_fu_215_p2();
    void thread_iy_fu_231_p2();
    void thread_iz_fu_261_p2();
    void thread_next_mul_fu_267_p2();
    void thread_p_i0_0_i1_cast3_fu_309_p1();
    void thread_p_i0_0_i_cast7_fu_188_p1();
    void thread_p_i0_2_fu_320_p2();
    void thread_p_i0_fu_199_p2();
    void thread_p_shl_i_fu_237_p3();
    void thread_p_x_assign_cast6_fu_205_p1();
    void thread_p_y_assign_cast5_fu_221_p1();
    void thread_pool_layer_2_2_1_10_10_16_input_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_input_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_d0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_we0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_input_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_input_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_input_data_V_d0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_input_data_V_we0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_output_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_output_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_output_data_V_d0();
    void thread_pool_layer_2_2_1_10_10_16_relu1_output_data_V_we0();
    void thread_tmp1_cast_fu_251_p1();
    void thread_tmp1_fu_245_p2();
    void thread_tmp2_fu_273_p2();
    void thread_tmp_3_i_fu_278_p2();
    void thread_tmp_4_i_fu_283_p1();
    void thread_tmp_77_fu_288_p1();
    void thread_tmp_78_fu_292_p3();
    void thread_tmp_fu_193_p2();
    void thread_tmp_s_fu_314_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
