// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _forward_pool_1_HH_
#define _forward_pool_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct forward_pool_1 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<11> > pool_layer_2_2_1_10_10_16_input_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_input_data_V_ce0;
    sc_in< sc_lv<16> > pool_layer_2_2_1_10_10_16_input_data_V_q0;
    sc_out< sc_lv<9> > pool_layer_2_2_1_10_10_16_output_data_V_address0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_output_data_V_ce0;
    sc_out< sc_logic > pool_layer_2_2_1_10_10_16_output_data_V_we0;
    sc_out< sc_lv<16> > pool_layer_2_2_1_10_10_16_output_data_V_d0;


    // Module declarations
    forward_pool_1(sc_module_name name);
    SC_HAS_PROCESS(forward_pool_1);

    ~forward_pool_1();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<9> > p_x_assign_cast7_fu_187_p1;
    sc_signal< sc_lv<9> > p_x_assign_cast7_reg_450;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<3> > o_y_fu_197_p2;
    sc_signal< sc_lv<3> > o_y_reg_458;
    sc_signal< sc_lv<32> > p_x_assign_5_cast_fu_211_p1;
    sc_signal< sc_lv<32> > p_x_assign_5_cast_reg_463;
    sc_signal< sc_lv<1> > exitcond2_fu_191_p2;
    sc_signal< sc_lv<32> > tmp_23_cast_fu_221_p1;
    sc_signal< sc_lv<32> > tmp_23_cast_reg_468;
    sc_signal< sc_lv<3> > o_x_fu_235_p2;
    sc_signal< sc_lv<3> > o_x_reg_476;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > h_3_cast_fu_249_p1;
    sc_signal< sc_lv<32> > h_3_cast_reg_481;
    sc_signal< sc_lv<1> > exitcond1_fu_229_p2;
    sc_signal< sc_lv<32> > tmp_24_cast_fu_267_p1;
    sc_signal< sc_lv<32> > tmp_24_cast_reg_486;
    sc_signal< sc_lv<9> > tmp2_cast_fu_277_p1;
    sc_signal< sc_lv<9> > tmp2_cast_reg_491;
    sc_signal< sc_lv<11> > next_mul2_fu_281_p2;
    sc_signal< sc_lv<11> > next_mul2_reg_496;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<9> > next_mul_fu_287_p2;
    sc_signal< sc_lv<9> > next_mul_reg_501;
    sc_signal< sc_lv<5> > ch_fu_299_p2;
    sc_signal< sc_lv<5> > ch_reg_509;
    sc_signal< sc_lv<32> > tmp_cast8_fu_305_p1;
    sc_signal< sc_lv<32> > tmp_cast8_reg_514;
    sc_signal< sc_lv<1> > exitcond_fu_293_p2;
    sc_signal< sc_lv<32> > tmp1_fu_314_p2;
    sc_signal< sc_lv<32> > tmp1_reg_522;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > tmp_23_fu_309_p2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > tmp_36_fu_399_p2;
    sc_signal< sc_lv<32> > h_fu_432_p2;
    sc_signal< sc_lv<32> > h_reg_535;
    sc_signal< sc_lv<32> > v_1_fu_438_p2;
    sc_signal< sc_lv<16> > avg_V_fu_444_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<3> > p_x_assign_reg_88;
    sc_signal< sc_lv<3> > p_y_assign_3_reg_99;
    sc_signal< sc_lv<5> > p_z_assign_reg_110;
    sc_signal< sc_lv<9> > phi_mul_reg_121;
    sc_signal< sc_lv<11> > phi_mul1_reg_133;
    sc_signal< sc_lv<16> > t_V_reg_144;
    sc_signal< sc_lv<32> > p_x_assign_3_reg_156;
    sc_signal< sc_lv<16> > p_Val2_s_reg_166;
    sc_signal< sc_lv<32> > p_y_assign_4_reg_178;
    sc_signal< sc_lv<64> > tmp_31_fu_329_p1;
    sc_signal< sc_lv<64> > tmp_38_fu_427_p1;
    sc_signal< sc_lv<4> > v_fu_203_p3;
    sc_signal< sc_lv<4> > tmp_21_fu_215_p2;
    sc_signal< sc_lv<4> > h_1_fu_241_p3;
    sc_signal< sc_lv<4> > tmp_22_fu_261_p2;
    sc_signal< sc_lv<5> > p_y_assign_3_cast6_fu_225_p1;
    sc_signal< sc_lv<5> > p_shl5_fu_253_p3;
    sc_signal< sc_lv<5> > tmp2_fu_271_p2;
    sc_signal< sc_lv<9> > tmp3_fu_319_p2;
    sc_signal< sc_lv<9> > tmp_29_fu_324_p2;
    sc_signal< sc_lv<17> > tmp_51_tr_fu_334_p1;
    sc_signal< sc_lv<17> > p_neg_fu_346_p2;
    sc_signal< sc_lv<15> > tmp_s_fu_352_p4;
    sc_signal< sc_lv<14> > tmp_30_fu_366_p4;
    sc_signal< sc_lv<16> > tmp_27_fu_362_p1;
    sc_signal< sc_lv<15> > tmp_32_fu_376_p1;
    sc_signal< sc_lv<1> > tmp_56_fu_338_p3;
    sc_signal< sc_lv<16> > tmp_33_fu_380_p2;
    sc_signal< sc_lv<16> > tmp_34_fu_386_p1;
    sc_signal< sc_lv<32> > tmp_57_fu_404_p2;
    sc_signal< sc_lv<32> > tmp_58_fu_410_p2;
    sc_signal< sc_lv<32> > tmp_fu_416_p2;
    sc_signal< sc_lv<32> > tmp_37_fu_422_p2;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_state6;
    static const sc_lv<7> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<11> ap_const_lv11_64;
    static const sc_lv<9> ap_const_lv9_19;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_avg_V_fu_444_p2();
    void thread_ch_fu_299_p2();
    void thread_exitcond1_fu_229_p2();
    void thread_exitcond2_fu_191_p2();
    void thread_exitcond_fu_293_p2();
    void thread_h_1_fu_241_p3();
    void thread_h_3_cast_fu_249_p1();
    void thread_h_fu_432_p2();
    void thread_next_mul2_fu_281_p2();
    void thread_next_mul_fu_287_p2();
    void thread_o_x_fu_235_p2();
    void thread_o_y_fu_197_p2();
    void thread_p_neg_fu_346_p2();
    void thread_p_shl5_fu_253_p3();
    void thread_p_x_assign_5_cast_fu_211_p1();
    void thread_p_x_assign_cast7_fu_187_p1();
    void thread_p_y_assign_3_cast6_fu_225_p1();
    void thread_pool_layer_2_2_1_10_10_16_input_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_input_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_address0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_ce0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_d0();
    void thread_pool_layer_2_2_1_10_10_16_output_data_V_we0();
    void thread_tmp1_fu_314_p2();
    void thread_tmp2_cast_fu_277_p1();
    void thread_tmp2_fu_271_p2();
    void thread_tmp3_fu_319_p2();
    void thread_tmp_21_fu_215_p2();
    void thread_tmp_22_fu_261_p2();
    void thread_tmp_23_cast_fu_221_p1();
    void thread_tmp_23_fu_309_p2();
    void thread_tmp_24_cast_fu_267_p1();
    void thread_tmp_27_fu_362_p1();
    void thread_tmp_29_fu_324_p2();
    void thread_tmp_30_fu_366_p4();
    void thread_tmp_31_fu_329_p1();
    void thread_tmp_32_fu_376_p1();
    void thread_tmp_33_fu_380_p2();
    void thread_tmp_34_fu_386_p1();
    void thread_tmp_36_fu_399_p2();
    void thread_tmp_37_fu_422_p2();
    void thread_tmp_38_fu_427_p1();
    void thread_tmp_51_tr_fu_334_p1();
    void thread_tmp_56_fu_338_p3();
    void thread_tmp_57_fu_404_p2();
    void thread_tmp_58_fu_410_p2();
    void thread_tmp_cast8_fu_305_p1();
    void thread_tmp_fu_416_p2();
    void thread_tmp_s_fu_352_p4();
    void thread_v_1_fu_438_p2();
    void thread_v_fu_203_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
